<a href="https://colab.research.google.com/github/SliwaSzubi/MLIntro/blob/master/spadek_gradientu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
import pandas as pd
import plotly.express as px

np.random.seed(42)

In [2]:
X1 = np.array([1,2,3,4,5,6])
Y = np.array([3000,3250,3500,3750,4000,4250])
m = len(X1)

print(f'Lata pracy: {X1}')
print(f'Wynagrodzenie: {Y}')
print(f'Liczba próbek: {m}')

Lata pracy: [1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczba próbek: 6


In [7]:
X1 = X1.reshape(m, 1)
Y = Y.reshape (-1, 1)

print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [8]:
bias = np.ones((m, 1))
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [9]:
X = np.append(bias, X1, axis = 1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


In [46]:
eta = 0.01
weights = np.random.randn(2, 1)
print(X)
print(weights)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
[[-1.01283112]
 [ 0.31424733]]


In [47]:
intercept = []
coef = []


for i in range(3000):
  gradient = (2 / m) * X.T.dot(X.dot(weights) - Y)
  weights = weights - eta * gradient
  intercept.append(weights[0][0])
  coef.append(weights[1][0])

print(weights)

[[2749.9559825 ]
 [ 250.01028158]]


In [48]:
df = pd.DataFrame(data={'intercept' : intercept, 'coef': coef})
df.head()

intercept        coef
0   71.485428  268.623157
1  123.752099  450.470153
2  162.244146  573.498226
3  191.354387  656.513341
4  214.071366  712.309487

In [49]:
px.line (df ,y='intercept', width=800, title='Dopasowanie: intercept')

In [50]:
px.line(df , y='coef', width=800, title='Dopasowanie: coef')